---
abstract: 'manage a collection of author tests shared between multiple projects'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XT-Manager
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  XT::Manager:
    file: lib/XT/Manager.pm
    version: 0.006
  XT::Manager::API:
    file: lib/XT/Manager/API.pm
    version: 0.006
  XT::Manager::API::Syntax:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::API::Types:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::Command:
    file: lib/XT/Manager/Command.pm
    version: 0.006
  XT::Manager::Command::pull:
    file: lib/XT/Manager/Command/pull.pm
    version: 0.006
  XT::Manager::Command::push:
    file: lib/XT/Manager/Command/push.pm
    version: 0.006
  XT::Manager::Command::remove:
    file: lib/XT/Manager/Command/remove.pm
    version: 0.006
  XT::Manager::Command::status:
    file: lib/XT/Manager/Command/status.pm
    version: 0.006
  XT::Manager::Comparison:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::Exception::FileNotFound:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::FileSystemTestSet:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::Repository:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::Test:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::TestSet:
    file: lib/XT/Manager/API.pm
    version: 0
  XT::Manager::XTdir:
    file: lib/XT/Manager/API.pm
    version: 0
requires:
  App::Cmd: 0.300
  Moo: 1.002000
  Path::Tiny: 0.017
  Syntax::Collector: 0.006
  Throwable: 0.200000
  Types::Standard: 0.004
  XT::Util: 0.001
  match::simple: 0.004
  thanks: 0.001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/XT-Manager/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XT-Manager
  homepage: https://metacpan.org/release/XT-Manager
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-xt-manager
version: 0.006
x_provides_scripts:
  perl-xt-manager:
    file: bin/perl-xt-manager
