---
abstract: 'manage a collection of author tests shared between multiple projects'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XT::Manager
name: XT-Manager
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Cmd: 0
  Moose: 2.00
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Syntax::Collector: 0.004
  Throwable: 0
  XT::Util: 0.001
  perl: 5.10.0
  thanks: 0.001
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XT-Manager
  homepage: https://metacpan.org/release/XT-Manager
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-xt-manager
version: 0.003
